
CREATE TABLE IF NOT EXISTS gamer (
		id bigint generated by default as identity,
		credit integer not null,
		gender varchar(255),
		geography varchar(255),
		name varchar(255),
		nickname varchar(255),
		user_id varchar(255) not null,
		primary key (id));
CREATE TABLE IF NOT EXISTS gamer_interest (
		id bigint generated by default as identity,
		level varchar(255),
		name varchar(255),
		gamer_id bigint not null,
		primary key (id));

alter table gamer add constraint UK_t77hvjxegfu4q27x9dmc3tbwl unique (user_id);
alter table gamer_interest add constraint FKhamx9flkvfnvbtb7i2sio405r foreign key (gamer_id) references gamer;